### ISSUE TITLE
Investigate whether to use identity hubs, orbit-db, or somehting else for storage backend 

### ISSUE THREAD

**Issue by oed** [uport-project/3box#1]
There are multiple options availible for us to use as a backend service. We want to be as flexible as possible, but most likely we will have to pick one and stick with it. Our choice should optimize for decentralization, privacy, and user sovereignty.

| Option | Comments |
| --- | --- |
| DIF Hub | Possibly great synergies as this standard emerges. Unclear exactly how decentralized these services will be. | 
| orbit-db | Uses ipfs and CRDTs. Using this we can utilize infura for ipfs hosting, and a thin service for keeping track of the most recent hash. This can easily be made more decentralized in the future. We would also need to roll our own system for maintaining the database. |
| swarm | Could be a great alternative, but api is quite hard to use currently | 
| BigchainDB | A premissioned DB system. Could be great if we want a DB that is shared between multiple people, but overkill for a personal data store. | 

So far I've seen no db with native encryption support.

**Comment by michaelsena** [comment]
What about BigchainDB @oed @ajunge

**Comment by oed** [comment]
@michaelsena added a small comment on bigchaindb

**Comment by c-castillo** [comment]
Should we timebox this research and set up a meeting to discuss pros and cons of each option? @oed @ajunge @michaelsena
