### ISSUE TITLE
Deploy the hash-server under the 3Box domain

### ISSUE THREAD

**Issue by ozlemulusoy** [uport-project/3box#129]

**Comment by michaelsena** [comment]
@c-castillo what credentials do you need here for the 3box.io domain?

**Comment by ajunge** [comment]
We need access to the domain. Is registered on namecheap? Under the Consensys account?

**Comment by c-castillo** [comment]
@michaelsena access to the domain. We need the domain records (basically, credentials to log in to manage the domain )

**Comment by michaelsena** [comment]
Ah, I see. I will provide access to credentials offline

**Comment by c-castillo** [comment]
New URL is [https://beta.3box.io](https://beta.3box.io)

I'll put this in review. Need for the DNS to propagate and verify on the JS library.

**Comment by oed** [comment]
@c-castillo I'm having problems with CORS errors. Getting a 502 on GET. Probably an easy fix when you get back :)

**Comment by c-castillo** [comment]
@oed Can you provide detailed info about the error? The CORS checks are in place.

**Comment by c-castillo** [comment]
@oed I reviewed one error. It wasn't CORS.
Now it's working properly. Tried with
https://beta.3box.io/hashserver/hash/0x12345
and got the expected response
