### ISSUE TITLE
Build Bug Reporting and Support MVP

### ISSUE THREAD

**Issue by ozlemulusoy** [uport-project/3box#148]
- [x] Dapp User Issue Reporting

- [x] 3Box DB Developer Issue Reporting

**Comment by ozlemulusoy** [comment]
Think about how this is different for dapp users and dev users.

**Comment by michaelsena** [comment]
https://airtable.com/shrX4fI8MDuaPpef9
@oed can you give the Dapp User side a run through?

Now I need to add a section to the "How to Contribute" doc about bug reports. Do you have any good examples from other projects we could use as a starting point?

**Comment by oznekenzo** [comment]
This airtable link is what we're going to link to from the drop down right @michaelsena

**Comment by michaelsena** [comment]
yep @oznekenzo :+1:
