### ISSUE TITLE
Clear out the userspace repo and put link to 3box in readme

### ISSUE THREAD

**Issue by oed** [uport-project/3box#167]
Should we do this after we release the mvp?

**Comment by michaelsena** [comment]
@oed can you check the repo and make sure this is what you meant by "clean out." 

Should we delete all the text in the readme except for the redirect, or should we leave the API spec? Wasn't sure.

**Comment by oed** [comment]
@michaelsena we should remove all text in the readme yeah. Also remove all files in the repo except the readme.
