### ISSUE TITLE
Publish "What is 3Box" article

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#174]
- [x] Draft article

- [ ] @oed review

- [ ] @christianlundkvist review

- [ ] Prepare final post on Medium

- [ ] Write 4 tweets

- [ ] Publish on uPort Medium publication

- [ ] Amplify across community channels

**Comment by michaelsena** [comment]
Article draft on medium: https://medium.com/@msena/distributed-database-infrastructure-for-ethereum-b9756ccde127

**Comment by michaelsena** [comment]
@christianlundkvist and @oed for your review :+1:

**Comment by oed** [comment]
Looks good, just left a small note.

**Comment by michaelsena** [comment]
you left the smallest note! :)
