### ISSUE TITLE
Publish "Ethereum Profiles API" article

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#176]

**Comment by ozlemulusoy** [comment]
Devs will provide input.

**Comment by michaelsena** [comment]
[Here is the first draft of the Medium post](https://medium.com/@3box/ethereum-profiles-api-54526eccd5cf) for @christianlundkvist and @oed review. If you want to make a lot of changes, feel free to copy to a Google Doc and work from there or whatever makes it easiest for you!

**Comment by oed** [comment]
I left some comments. I also a general thing. Right now we have:
`box.profileStore.get` and `box.privateStore.get`
What do you think about changing this to the more simple:
`box.public.get` and `box.private.get`
I think this makes things a bit more clear, and it's a simple change :)

**Comment by oed** [comment]
@michaelsena sweet, I'll create a story for that change :)

**Comment by michaelsena** [comment]
Final draft of the article, last call for reviews! 3️⃣This will go out tomorrow morning ~10am unless major revisions https://medium.com/uport/ethereum-profiles-api-54526eccd5cf
