### ISSUE TITLE
Define acceptance criteria for "clean, documented MVP"

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#178]

**Comment by michaelsena** [comment]
Here's the acceptance criteria for MVP. I think they're all there. Don't think we need to spend too much time here because I think we're aligned, but prob worth a look to be sure! https://docs.google.com/document/d/1FjBp3b8n9SYMADMG6NRsMuhZuu0NIphhYRtszWBjurc/edit?usp=sharing

**Comment by michaelsena** [comment]
@oed @c-castillo @oznekenzo ready for your beautiful eyes!

**Comment by oed** [comment]
👍

**Comment by oznekenzo** [comment]
🙌

**Comment by oznekenzo** [comment]
@michaelsena In the education section, do you want to put anything about learning how to use the activity library?

Also, there isn't any documentation for the activity library yet! :]
