### ISSUE TITLE
Create marketing assets

### ISSUE THREAD

**Issue by ozlemulusoy** [uport-project/3box#180]

**Comment by oed** [comment]
I don't know if it should be part of this story or not, but we need dev stickers to hand out at events! One problem though, it would be ideal if they where hexagons, while our logo is a square. I'm not saying we should change our logo, just need a different concept for the hex devstickers. hexes can be easily made to look like boxes btw, see ipfs logo:
 ![](https://raw.githubusercontent.com/ipfs/logo/master/raster/ipfs-logo-icewithbg-128.png) 

cc @michaelsena

**Comment by oed** [comment]
![3box-dev-concept](https://user-images.githubusercontent.com/3909429/45597472-3a290080-b9cd-11e8-8ad9-67de2c639b10.png)
I'm thinking something like this. Just something to give to other devs :)

**Comment by oznekenzo** [comment]
As per @michaelsena 
Twitter: Banner Image, User Image for @3boxdb
Medium: User Image for @3box
Discord: User Image for Discord Server

**Comment by michaelsena** [comment]
This looks good to me, thanks @oznekenzo !

**Comment by michaelsena** [comment]
@oznekenzo you can move this to done whenever!
