### ISSUE TITLE
Clean up Tech Spec

### ISSUE THREAD

**Issue by ozlemulusoy** [uport-project/3box#185]

**Comment by ozlemulusoy** [comment]
Oed and Christian need to have a conversation about lpld

**Comment by oed** [comment]
* https://github.com/uport-project/3box/blob/master/ARCHITECTURE.md 
Needs to be updated. Most of the stuff is already in the [data schema](https://github.com/uport-project/3box-js/blob/develop/DATA-SCHEMA.md) file in the 3box-js library.

* https://github.com/uport-project/3box/blob/master/ABOUT.md 
Can be removed?

*

**Comment by oed** [comment]
Yes, seems like we can remove the DATA-SCHEMA file. I still think that the ARCHITECTURE file should live in the 3box repo though, since it also includes information about the server side components. We can have a link to it from the 3box-js repo.
