### ISSUE TITLE
Complete legal work for MVP

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#186]
* terms of service
* privacy policy
 etc

**Comment by michaelsena** [comment]
LegL has started the wheels in motion on this stuff

**Comment by michaelsena** [comment]
Had the kickoff meeting with David @ ConsenSys legl, and he's going to be following up with emails. I will continue to work with him on this.

**Comment by oed** [comment]
All in order? Anything worth noting?

**Comment by michaelsena** [comment]
Nothing really worth noting, he likes the idea and is going to sync with Joyce on GDPR compliance. Joyce helped uPort with GDPR stuff, so she's up to speed. David said he was going to take inspo from dropbox and other similar companies.

**Comment by michaelsena** [comment]
I scheduled a conversation with the legal team for tomorrow to discuss GDPR and how, if at all, it affects us.

**Comment by oed** [comment]
Good. Do you need any input to that, or do you have everything you need for that convo?
