### ISSUE TITLE
Write JD for Growth position

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#204]

**Comment by michaelsena** [comment]
Here is the draft for your review @oed @c-castillo https://docs.google.com/document/d/1IFAtica0e8z9l0_mcKxuZug1xutL4JA7po3zGe9U_NE/edit?usp=sharing

**Comment by oed** [comment]
Looks good! So this supersedes the "technical community manager" role right?

**Comment by michaelsena** [comment]
@oed I see them as two distinct roles, with growth superseding community management. Growth is more of a priority right now though, and we can delay bringing on a community manager if we can fill this position first.

**Comment by michaelsena** [comment]
Yup, let's sync on this after tomorrow
