### ISSUE TITLE
Order t-shirts for devcon and retreat

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#206]

**Comment by michaelsena** [comment]
<img width="594" alt="screen shot 2018-09-30 at 3 33 05 pm" src="https://user-images.githubusercontent.com/5216274/46261787-74fb6000-c4c6-11e8-9abf-615da6d4e694.png">

Thoughts?

**Comment by michaelsena** [comment]
<img width="601" alt="screen shot 2018-09-30 at 3 44 29 pm" src="https://user-images.githubusercontent.com/5216274/46261899-07503380-c4c8-11e8-9d4c-ebf9e410fc2e.png">

Thoughts on 2?

**Comment by michaelsena** [comment]
<img width="863" alt="screen shot 2018-09-30 at 4 07 30 pm" src="https://user-images.githubusercontent.com/5216274/46262122-fa810f00-c4ca-11e8-8cf1-83441876a829.png">

Thoughts on 3?

**Comment by oed** [comment]
3 all the way 😄

**Comment by oed** [comment]
Maybe we could make the 3️⃣ logo larger?

**Comment by michaelsena** [comment]
<img width="862" alt="screen shot 2018-10-01 at 7 28 53 am" src="https://user-images.githubusercontent.com/5216274/46286073-bda92c80-c54b-11e8-8626-5058565b2b8a.png">

gradient in our color scheme - take 4 (cc @oed)

**Comment by oed** [comment]
@michaelsena I liked that the previous one blended more colors 🙂

**Comment by oed** [comment]
Since this shirt is for **devcon 4** (not devcon 3 as on the shirt in the picture;) ) It would be cool if we followed their color gradient: https://devcon4.ethereum.org/

**Comment by oed** [comment]
Maybe even do a white shirt to completely follow their color scheme?

**Comment by michaelsena** [comment]
Okay, so here are all the options 👍 
![group 12](https://user-images.githubusercontent.com/5216274/46290548-2697a100-c55a-11e8-8019-665df7992e10.png)

**Comment by oed** [comment]
I prefer 1 over 3. 2 is on the back right? 
<3 Deva
Haight is also nice :)

**Comment by oed** [comment]
Ok, yeah that makes sense I guess.
Not sure which one I like the most of the deva vs deva on haight 🙂

**Comment by c-castillo** [comment]
Like them all. Deva on Haight and BoxCon are my favorites

**Comment by zachferland** [comment]
Like any of them, just prefer a black shirt, hate white ones

**Comment by oed** [comment]
I guess we could do both :)

**Comment by michaelsena** [comment]
Yeah I'll construct an order of our favorites and repost here before I place, so everyone can make sure they approve.

**Comment by zachferland** [comment]
I'll wear any shirt we make, I ll just wear a black one more ❤️

**Comment by michaelsena** [comment]
Final Draft:
![devcon4-shirts](https://user-images.githubusercontent.com/5216274/46316858-49987400-c59f-11e8-8e4c-0957e34edc40.png)

**Comment by michaelsena** [comment]
@oznekenzo would love your input here too :heart:
