### ISSUE TITLE
3Box DB Speed

### ISSUE THREAD

**Issue by oed** [uport-project/3box#229]
Make openBox & getProfile faster

**Comment by KamesCG** [comment]
How?

Do you just want to create the actual initialization faster, and if so what's the best place I can start diving into to help?

Additionally, thoughts on providing a caching mechanism to provide the appearance of instant loading? It might not provide any significant for small amounts of data, but what about `diffing` cached data with data references on IPFS to only request data if it's been changed in circumstances where a significant amount of data is being requested?

**Comment by oed** [comment]
@KamesCG This is an epic. If you open it in zenhub you will see a lot of stories associated with it. Building a caching layer is something that we are considering to do later on.
