### ISSUE TITLE
Organize 3Box Devcon/Retreat

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#232]

**Comment by oed** [comment]
I have a session I'm planning currently. It will be "crypto ceremonial magic" and will likely take 1-3 h

**Comment by zachferland** [comment]
any more details on this "ceremonial crypto magic" :) ?

**Comment by oed** [comment]
As any serious magic it can only be revealed it to initiates 😜 You'll get more info when needed 🙂

**Comment by zachferland** [comment]
haha I will ponder it till then
