### ISSUE TITLE
Add shields to all repos

### ISSUE THREAD

**Issue by ozlemulusoy** [uport-project/3box#247]

**Comment by michaelsena** [comment]
@zachferland this looks good, now guessing we have to add them to every repo.

**Comment by michaelsena** [comment]
ping @zachferland are we good to go here? 👍

**Comment by zachferland** [comment]
wasn't going to add to the other repos, but actually still makes sense to add twitter and chat (all other shields can be added later if configured (coverages, builds, etc) add those right now

**Comment by oed** [comment]
Is this story done?

**Comment by zachferland** [comment]
yup

**Comment by zachferland** [comment]
yup
