### ISSUE TITLE
Create a secondary environment

### ISSUE THREAD

**Issue by c-castillo** [uport-project/3box#250]

**Comment by c-castillo** [comment]
`/ip4/127.0.0.1/tcp/4003/ws/ipfs/QmeKVVw1yhVGncoAGXhKMDqgeymujuKZAdkaqW9L1FKfq8`

**Comment by oed** [comment]
@c-castillo that's the localhost ip? I guess we don't need to expose this publicly though?

**Comment by c-castillo** [comment]
We need the ip to stress it from the client side.
`/ip4/34.219.25.216/tcp/4003/ws/ipfs/QmeKVVw1yhVGncoAGXhKMDqgeymujuKZAdkaqW9L1FKfq8`
