### ISSUE TITLE
Write Bounties for Status

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#279]

**Comment by oed** [comment]
@jjperezaguinaga This story is for creating bouties for the https://prague.bounties.network/ 👍🏻

**Comment by jjperezaguinaga** [comment]
@oed I see, good to know! Would love to hear your experience about how to use Bounties Network. Are you able to generate a subdomain without any support from the Bounties Network team?

**Comment by michaelsena** [comment]
closing, as we didn't post bounties for the status cryptolife hackathon
