### ISSUE TITLE
Build caching service for getProfile

### ISSUE THREAD

**Issue by oed** [uport-project/3box#281]
Currently `Box.getProfile` can be quite slow, to get around this we should make a centralized caching service as a REST api that you can query with ethereum addresses and get public profiles back. The service would have tree components:
* An ipfs/orbitdb node
* A database
* A REST API with serverless

The ipfs/orbitdb node would be similar to the pinning-server but it only listens for changes to the public stores of users. When there is an update it will update the database. The REST API would query the database and return users profiles. The API would have two endpoints like this:

`GET /get-profile/`
#### Body
```
{
  address: <ethereum-address>,
  keys: <an array of keys to return>
}
```

`GET /get-profiles/`
#### Body
```
{
  addresses: <an array of ethereum-addresses>,
  keys: <an array of keys to return>
}
```
`keys` can be things like `name` and `image`, if left blank the entire profile will be returned.

**Comment by rej156** [comment]
GraphQL endpoint please
