### ISSUE TITLE
Updated contributor guidelines on CONTRIBUTING.md

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#293]
https://github.com/uport-project/3box/blob/master/CONTRIBUTING.md

**Comment by christianlundkvist** [comment]
Between `CONTRIBUTING.md` and `REPO-BEST-PRACTICES.md` there was not much extra needed. Just added some general pointers about bug reporting and linting.

This is the PR:

https://github.com/uport-project/3box/pull/348

**Comment by christianlundkvist** [comment]
Added a contribution file in the following PR:

https://github.com/uport-project/3box-js/pull/183
