### ISSUE TITLE
Build signup capture method for community call #2

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#320]
* Kickback?
* Airtable?
* Mailchimp page?

We want to capture emails and names, so we can follow up with them, but we don't want to add unnecessary friction. Thinking something like users sign up, and immediately see a [link to the open gcal event](https://calendar.google.com/event?action=TEMPLATE&tmeid=ZjB2YW45dmRnZGIyMGE4ZWpvcDIycWxhY2sgY29uc2Vuc3lzLm5ldF9uZ2JxNGhmZjl1c2l2azQxbDE2anQwZW9tOEBn&tmsrc=consensys.net_ngbq4hff9usivk41l16jt0eom8%40group.calendar.google.com). Which when clicked, adds it to their calendar.

**Comment by dazuck** [comment]
@michaelsena can you check and update the mailchimp signup in 1pass? I think we should just use malichimp so we keep it all in one place. Can set up but don't have access now

**Comment by michaelsena** [comment]
@dazuck will share the login credentials for mailchimp in 1PW, but in the meantime I created a new community call list and signup flow. LMK thoughts! http://eepurl.com/dOmdjv

**Comment by dazuck** [comment]
looks great. that is feeding directly into mailchimp list? 👍

**Comment by michaelsena** [comment]
@dazuck yup
