### ISSUE TITLE
Add "Team" section for open jobs to 3box.io site

### ISSUE THREAD

**Issue by dazuck** [uport-project/3box#352]
Probably just in the footer - any place people can find our listings directly not just via Consensys.

**Comment by dazuck** [comment]
@michaelsena @oznekenzo  not urgent but something for the backlog to do a quick MVP version when possible.

**Comment by oed** [comment]
Can't we just add a file in the 3box repo for team for now?

**Comment by dazuck** [comment]
@oed that's fine. Also @michaelsena  pointed out that I had missed a separate story that tackles this generally so I'll just close this for now.
