### ISSUE TITLE
Research data schemas

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#54]

**Comment by oed** [comment]
What are we aiming at here? This could be really broad. Is it schemas for stuff being used in web3 atm? General data schemas currently used on the web? 
For what kind of data? User profiles? Behvioural data? Personal data? Health data? etc.
I guess it really depends a lot on what we end up aiming for. But I guess this is mostly about what people in the web3 space are doing currently?

**Comment by oed** [comment]
Research on user profiles in dapp browsers & general:
https://docs.google.com/document/d/1Md4cz1-dZ-rDTMcVYIYlLxLU644s6iVN4C-apng6SDk/edit?usp=sharing

**Comment by michaelsena** [comment]
Thanks @oed - at least we know there isn’t much we have to worry about breaking!
