### ISSUE TITLE
Spec "Profile" data schema/guide that we will use for our Profile

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#57]
Spec document is here:

https://docs.google.com/document/d/1c68Hh3-1HZRLWQV5uLmt7tARrTEnPXIkmaB0fYZlgWU

**Comment by dazuck** [comment]
@christianlundkvist any reason we shouldn't use [schema.org Person ](https://github.com/blockstack/blockstack.js/blob/master/src/profiles/README.md#blockstack-profiles)to start, like Blockstack? 

I think there's going to be immediate demand for expanding our starting fields (name, avatar) with more self-attested info. Starting on schema.org gives us an easy way to expand (or let others expand) in a way that doesn't get out of hand.

**Comment by christianlundkvist** [comment]
This is the relevant Blockstack Profiles stuff:

https://github.com/blockstack/blockstack.js/tree/master/src/profiles

We can just use what they have there to start with.

**Comment by oed** [comment]
@christianlundkvist are you saying that we store the public profile as an ipld object instead of in an orbit-db? I think that would be interesting since lookups will probably be much faster, but I'm not a 100% sure yet.

**Comment by christianlundkvist** [comment]
@oed Yeah I was thinking that it could be an IPLD object since I would not expect there to be too much data to store in there?
