### ISSUE TITLE
Define criteria for prioritization/evaluation

### ISSUE THREAD

**Issue by dazuck** [uport-project/3box#58]
1) When do we know that the market driven approach has driven us too far from what we're trying to do? 

2) ---> how do we prioritize product opportunities for market opp + mission alignment 

3) validate who cares about user-controlled data, why + when

**Comment by michaelsena** [comment]
How are you feeling about this? @dazuck

**Comment by dazuck** [comment]
@michaelsena sorry hadn't posted here just in slack: https://docs.google.com/document/d/1ByLQf3LkJjchQzlErRtc4OB7omafADCnBwPE_pPNWxU/edit#
