### ISSUE TITLE
Wallet/Web3 Provider Technical Research

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#61]

**Comment by ajunge** [comment]
Status of eth_sign and eth_encrypt

Research:
- Metamask
- Cipher
- Trustwallet
- uPort

**Comment by ajunge** [comment]
This looks like the standard https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md

**Comment by michaelsena** [comment]
Is there a document containing these findings @ajunge, so we can add it to the research index

**Comment by ajunge** [comment]
https://docs.google.com/document/d/1fgHX9CQxs-k8qqmiisxZldbTOrMryoRV5zNhWtkD9XE/
