### ISSUE TITLE
Research state channel storage options

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#62]
Evaluate how Raiden and Spankchain are storing data related to the state channel, and determine if what would be required to support these state channel usecases.

Is there anything here with Plasma, too?

**Comment by oed** [comment]
Research findings:
https://docs.google.com/document/d/1IwSSWY9bCxGm5_bbCLV2FWuOq8M5uW814nAKz13mlA0/edit?usp=sharing
I could dive deeper into different plasma implementations, but it doesn't feel necessary at this point.

**Comment by ajunge** [comment]
@oed check: https://docs.connext.network/

**Comment by michaelsena** [comment]
Looks good @oed thanks for gathering this info. We should have a convo with spankchain when we’re more developed with our initial use cases and begin looking to expand 3box functionality
