### ISSUE TITLE
Path forward communications

### ISSUE THREAD

**Issue by dazuck** [uport-project/3box#66]
--Thank / follow up with interviewees
--Set up bi-weekly release notes / communication 
-- integrate with x-team

**Comment by dazuck** [comment]
@michaelsena Here's what I'm thinking for this. 

1. Follow up with everyone we've interviewed so far (short, personal email) and tell them: 
(a) thank you + a small token gift for their time
(b) our rough plan for next steps (public profile backed by private data)  
(c) that we'll plan to keep them updated with release notes 1-2/month (if they opt in) 

2. Start + maintain a super-light CRM of our interviewees/customers (likely airtable, possibly SF) and coming out of retro each week we send release notes (and possibly video of demos?) to all 
** we can segment the CRM a little (e..g, expressed interest in [profiles] [contacts] etc. in case we start to worry we are spamming too much. But 
*Q: Do you think we should send by email or put on our (tbd) site or put on Medium and send a link to that? 

3. Tell plan to IIS+x-team and offer for them (X) to join/manage. 

cc @oed b/c you have strong thoughts on community

**Comment by michaelsena** [comment]
What do you think 1C is (the "thank you token")? What is a thank you token? An ERC721? ETH? A token of our appreciation? :) @dazuck

**Comment by michaelsena** [comment]
We should also ask the ones we're interested in following up closely with if we can schedule a next checkin sometime in the future just to get something on the calendar and keep up momentum? (TMNT, Bounties)

**Comment by michaelsena** [comment]
I would think there is no harm in duplication the release notes on Medium and Email for those who have opted in, and I like the idea of segmenting according to desired features, as well as type of dapp

**Comment by dazuck** [comment]
lol @michaelsena i just meant a 'token of appreciation' gift, not an ERC token. But we could start sending BCK ? 

Cool. I'll set up an airtable or something for the email list early next week. WIll check in with Alice/Kames/Mauricio about whether to do it jointly with other things, but probably start with our own basic one and merge later if so.
