### ISSUE TITLE
Build public profile

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#71]
Implementation todo list:

- [ ] Calling `openBox` should request a signature from MM, from that signature a muportDID should be created (code for this is already in the repo, might need some cleanup)
- [ ] Calling `set`on ProfileStore the first time should create the profile ipfs document, and the root ipfs object. Then publish that hash to `3box-root-hash-tracker` (gets associated to the muportDID). Finally link the ethereum address to the muportDID by signing data as specified in the `3box-root-hash-tracker` specification and send it to the server.
- [ ] Any subsequent call to `openBox` should check first if the muportDID has been saved in localstorage (it has to be saved the first time). Some non-finished code exists in 3box-js already
- [ ] Any subsequent call to `set` or `remove` on the profile should result in an updated ipfs root object, the hash of which should be sent to the `3box-root-hash-tracker`.

This is a partial list. Will upgrade as I go. //oed

**Comment by oed** [comment]
Added a todo list with important implementation details.

**Comment by oed** [comment]
Useful links:
https://github.com/orbitdb/orbit-db/blob/master/API.md#orbitdbkeyvaluenameaddress
https://github.com/orbitdb/orbit-db/issues/425#issuecomment-410843782

**Comment by michaelsena** [comment]
@christianlundkvist and here too. <3

**Comment by christianlundkvist** [comment]
Again would be good to know what we are doing code review on. Is there a block of code in a stable state that can be reviewed?
