### ISSUE TITLE
3Box Dapp Wireframes

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#74]

**Comment by michaelsena** [comment]
Posted first version in slack, it's not at a URL so couldn't quickly post here. Got good feedback from @dazuck @oed @KamesCG and will revise based on that feedback. Will have another version for review on Monday

**Comment by oed** [comment]
![image](https://user-images.githubusercontent.com/3909429/44296020-8e00d680-a2b5-11e8-9ac6-84941e12a656.png)
@michaelsena :P
