### ISSUE TITLE
Implement Public Profile Developer API

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#81]

**Comment by oed** [comment]
see: https://github.com/uport-project/3box-js

**Comment by michaelsena** [comment]
@christianlundkvist can you please see if we need any help here with @ajunge out? Want to make sure this doesn't fall through.

**Comment by christianlundkvist** [comment]
So this issue is under “Code Review”, but what are we reviewing? All the code in 3box-js? There is no specific pull request there.
