### ISSUE TITLE
Implement web3 Public Profile Consent dialog

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#83]

**Comment by oed** [comment]
This is only what the text in the dialog boxes should be right?
There are two different consent types that the user can give:
* Consent to read/update/delete private data, and update/delete profile data
* Consent to publishing a profile that is associated to the users ethereum address

So we need texts for these that a user can understand. Unfortunately we won't be able to have clickable links in these dialogs.

**Comment by michaelsena** [comment]
@oed do we need the copy for this?
