### ISSUE TITLE
Research how to make block explorer data available to client library users

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box#84]
*Etherscan
*Infura
*EthQL
*Quickblocks
*Alethio

**Comment by dazuck** [comment]
Perhaps helpful? https://medium.com/dsys/ethereum-meet-graphql-c28f3402fe8f

**Comment by michaelsena** [comment]
Can we have?
- token metadata
- contract nametags
- verified contracts
- token names
- dapps
- function names
- uPort AppManager Dapp IDs
