### ISSUE TITLE
Research Infura pinning

### ISSUE THREAD

**Issue by ozlemulusoy** [uport-project/3box#88]
Check if infura automatically pins added ipfs objects.

**Comment by oed** [comment]
I guess we just need to ask the infura team.

**Comment by c-castillo** [comment]
They have an API method to allow pinning on their IPDS gateway:
`https://infura.io/docs/ipfs/get/pin_add`

**Comment by oed** [comment]
Yes, but usually there is an option to pin direct when you add an object.
By default it can be either true or false. I think they have it set to
true, but we need to ask :)

**Comment by c-castillo** [comment]
pin [Optional] - Pin this object when adding. Default: “true”.

Yes, even easier.
